
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form Principal2
     */
    public Principal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInversionI = new javax.swing.JTextField();
        txtInversionII = new javax.swing.JTextField();
        txtInversionIII = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPorcentajeI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPorcentajeII = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPorcentajeIII = new javax.swing.JTextField();
        cdmCalcular = new javax.swing.JButton();
        cdmBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSumatoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("INVERSIÓN PARA FUNDAR UNA EMPRESA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 420, 30));

        jLabel2.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel2.setText("Inversión I");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel8.setText("Inversión II");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel9.setText("Inversión III");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtInversionI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInversionIActionPerformed(evt);
            }
        });
        txtInversionI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInversionIKeyTyped(evt);
            }
        });
        getContentPane().add(txtInversionI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, -1));

        txtInversionII.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInversionIIKeyTyped(evt);
            }
        });
        getContentPane().add(txtInversionII, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, -1));

        txtInversionIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInversionIIIActionPerformed(evt);
            }
        });
        txtInversionIII.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInversionIIIKeyTyped(evt);
            }
        });
        getContentPane().add(txtInversionIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));

        jLabel10.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel10.setText("Porcentaje Inversión I");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        txtPorcentajeI.setEditable(false);
        getContentPane().add(txtPorcentajeI, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 140, -1));

        jLabel11.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel11.setText("Porcentaje Inversión II");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 20));

        txtPorcentajeII.setEditable(false);
        getContentPane().add(txtPorcentajeII, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, -1));

        jLabel12.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel12.setText("Porcentaje Inversión III");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        txtPorcentajeIII.setEditable(false);
        getContentPane().add(txtPorcentajeIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 140, -1));

        cdmCalcular.setText("CALCULAR");
        cdmCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cdmCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        cdmBorrar.setText("BORRAR");
        cdmBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cdmBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel3.setText("Operación:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 80, -1));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Porcentaje" }));
        getContentPane().add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel4.setText("Sumatoria");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        txtSumatoria.setEditable(false);
        txtSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSumatoriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSumatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInversionIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInversionIActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtInversionIActionPerformed

    private void txtInversionIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInversionIKeyTyped
        // TODO add your handling code here:

        char c=evt.getKeyChar();

        if(!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
    }//GEN-LAST:event_txtInversionIKeyTyped

    private void txtInversionIIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInversionIIKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtInversionIIKeyTyped

    private void txtInversionIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInversionIIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInversionIIIActionPerformed

    private void txtInversionIIIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInversionIIIKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtInversionIIIKeyTyped

    private void cdmCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmCalcularActionPerformed
        // TODO add your handling code here:
        String n1,n2,n3 = null, resultado,res,res3,resS;
        double num1 = 1, num2=1, num3=1, por1, por2, por3, resul = 0;
        

        if (txtInversionI.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la Inversión I", "Error",JOptionPane.ERROR_MESSAGE);
            txtInversionII.requestFocusInWindow();
        } else if (txtInversionII.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la inversion II", "Error",JOptionPane.ERROR_MESSAGE);
            txtInversionII.requestFocusInWindow();
            if (txtInversionIII.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la inversion III", "Error",JOptionPane.ERROR_MESSAGE);
            txtInversionIII.requestFocusInWindow();

        }else {
            num1 = Double.parseDouble(txtInversionI.getText());
            num2 = Double.parseDouble(txtInversionII.getText());
            num3 = Double.parseDouble(txtInversionIII.getText());
            

           
        }
        
            resul = num1+num2+num3;
            res =  String.valueOf(resul);
            txtSumatoria.setText(res);
            
            por1=num1*100/resul;
            res =  String.valueOf(por1);
            txtPorcentajeI.setText(res);
            
            por2= num2*100/resul;
            res =  String.valueOf(por2);
            txtPorcentajeII.setText(res);
            
            por3= num3*100/resul;
            res =  String.valueOf(por3);
            txtPorcentajeIII.setText(res);
         
          
        }
    }//GEN-LAST:event_cdmCalcularActionPerformed

    private void cdmBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmBorrarActionPerformed
        // TODO add your handling code here:
        txtInversionI.setText("");
        txtInversionII.setText("");
        txtInversionIII.setText("");
        txtPorcentajeI.setText("");
        txtPorcentajeII.setText("");
        txtPorcentajeIII.setText("");

        txtInversionI.requestFocusInWindow();
       

    }//GEN-LAST:event_cdmBorrarActionPerformed

    private void txtSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSumatoriaActionPerformed
        // TODO add your handling code here:
        
        String n1,n2,n3 = null, resultado,res;
        double num1 = 1, num2=1, num3=1, por1, por2, por3, resul = 0,result, suma;
        
        suma = num1+num2+num3;
        res= String.valueOf(suma);
        txtSumatoria.setText(res);
        
        
    }//GEN-LAST:event_txtSumatoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdmBorrar;
    private javax.swing.JButton cdmCalcular;
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtInversionI;
    private javax.swing.JTextField txtInversionII;
    private javax.swing.JTextField txtInversionIII;
    private javax.swing.JTextField txtPorcentajeI;
    private javax.swing.JTextField txtPorcentajeII;
    private javax.swing.JTextField txtPorcentajeIII;
    private javax.swing.JTextField txtSumatoria;
    // End of variables declaration//GEN-END:variables
}
