
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInversionI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtInversionII = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtInversionIII = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPorcentajeI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPorcentajeII = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPorcentajeIII = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtResultadoI = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtResultadoIII = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtResultadoII = new javax.swing.JTextField();
        cdmCalcular = new javax.swing.JButton();
        cdmBorrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("INVERSIÓN PARA FUNDAR UNA EMPRESA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 420, 30));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel2.setText("Inversión I");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtInversionI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInversionIActionPerformed(evt);
            }
        });
        add(txtInversionI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, -1));

        jLabel8.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel8.setText("Inversión II");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        add(txtInversionII, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 60, -1));

        jLabel9.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel9.setText("Inversión III");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtInversionIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInversionIIIActionPerformed(evt);
            }
        });
        add(txtInversionIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));

        jLabel10.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel10.setText("Porcentaje Inversión I");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
        add(txtPorcentajeI, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 60, -1));

        jLabel11.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel11.setText("Porcentaje Inversión II");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 20));
        add(txtPorcentajeII, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 60, -1));

        jLabel12.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel12.setText("Porcentaje Inversión III");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));
        add(txtPorcentajeIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 60, -1));

        jLabel13.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel13.setText("Resultado Porcentaje I");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        add(txtResultadoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 60, 20));

        jLabel14.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel14.setText("Resultado Porcentaje III");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));
        add(txtResultadoIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 60, -1));

        jLabel15.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel15.setText("Resultado Porcentaje II");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));
        add(txtResultadoII, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 60, -1));

        cdmCalcular.setText("CALCULAR");
        cdmCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmCalcularActionPerformed(evt);
            }
        });
        add(cdmCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        cdmBorrar.setText("BORRAR");
        add(cdmBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cdmCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmCalcularActionPerformed
        // TODO add your handling code here:
        String n1,n2,n3, resultado;
        
    }//GEN-LAST:event_cdmCalcularActionPerformed

    private void txtInversionIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInversionIIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInversionIIIActionPerformed

    private void txtInversionIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInversionIActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtInversionIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdmBorrar;
    private javax.swing.JButton cdmCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtInversionI;
    private javax.swing.JTextField txtInversionII;
    private javax.swing.JTextField txtInversionIII;
    private javax.swing.JTextField txtPorcentajeI;
    private javax.swing.JTextField txtPorcentajeII;
    private javax.swing.JTextField txtPorcentajeIII;
    private javax.swing.JTextField txtResultadoI;
    private javax.swing.JTextField txtResultadoII;
    private javax.swing.JTextField txtResultadoIII;
    // End of variables declaration//GEN-END:variables
}
